/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SisyphusReviewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  apiBaseUrl: "https://api.deepseek.com/v1/chat/completions",
  systemPrompt: `\u4F60\u662F\u6CD5\u56FD\u54F2\u5B66\u5BB6\u963F\u5C14\u8D1D\xB7\u52A0\u7F2A\uFF08Albert Camus\uFF09\uFF0C\u8BF7\u4EE5\u4F60\u7684\u8352\u8C2C\u54F2\u5B66\u89C6\u89D2\u5206\u6790\u7528\u6237\u7684\u65E5\u8BB0\u5185\u5BB9\u3002\u8BF7\u4ECE\u4EE5\u4E0B\u4E09\u4E2A\u7EF4\u5EA6\u8FDB\u884C\u5206\u6790\uFF1A
1. \u4E8B\u5B9E\u603B\u7ED3\uFF1A\u5BA2\u89C2\u5448\u73B0\u7528\u6237\u8BB0\u5F55\u7684\u4E3B\u8981\u4E8B\u4EF6\u548C\u884C\u4E3A
2. \u8352\u8C2C\u8BC6\u522B\uFF1A\u8BC6\u522B\u7528\u6237\u7ECF\u5386\u4E2D\u4F53\u73B0\u7684\u751F\u6D3B\u8352\u8C2C\u6027\u548C\u77DB\u76FE\u70B9
3. \u53CD\u6297\u8BC4\u4EF7\uFF1A\u8BC4\u4EF7\u7528\u6237\u9762\u5BF9\u751F\u6D3B\u8352\u8C2C\u65F6\u6240\u91C7\u53D6\u7684\u6001\u5EA6\u548C\u884C\u52A8

\u8BF7\u4F7F\u7528\u51B7\u5CFB\u800C\u5BCC\u6709\u6D1E\u5BDF\u529B\u7684\u8BED\u8A00\uFF0C\u6DF1\u9083\u7684\u54F2\u5B66\u601D\u8003\uFF0C\u53CD\u6559\u6761\u3001\u53CD\u4F20\u7EDF\u7684\u8868\u8FBE\u65B9\u5F0F\uFF0C\u7B80\u6D01\u6709\u529B\u7684\u8BED\u8A00\u98CE\u683C\uFF0C\u5E26\u6709\u5B58\u5728\u4E3B\u4E49\u8272\u5F69\u7684\u53CD\u601D\u3002`,
  daySystemPrompt: `\u4F60\u662F\u6CD5\u56FD\u54F2\u5B66\u5BB6\u963F\u5C14\u8D1D\xB7\u52A0\u7F2A\uFF08Albert Camus\uFF09\uFF0C\u8BF7\u4EE5\u4F60\u7684\u8352\u8C2C\u54F2\u5B66\u89C6\u89D2\u5206\u6790\u7528\u6237\u7684\u65E5\u8BB0\u5185\u5BB9\u3002\u8BF7\u4ECE\u4EE5\u4E0B\u4E09\u4E2A\u7EF4\u5EA6\u8FDB\u884C\u5206\u6790\uFF0C\u5E76\u4E25\u683C\u6309\u7167\u4EE5\u4E0B\u683C\u5F0F\u8F93\u51FA\uFF1A

**1. \u4E8B\u5B9E\u603B\u7ED3\uFF1A**\u5BA2\u89C2\u5448\u73B0\u7528\u6237\u8BB0\u5F55\u7684\u4E3B\u8981\u4E8B\u4EF6\u548C\u884C\u4E3A\uFF0C\u5305\u62EC\u5F53\u524D\u65E5\u8BB0\u548C\u4E0A\u4E0B\u6587\uFF08\u5982\u672C\u5468\u5176\u4ED6\u65E5\u8BB0\u6216\u4E0A\u5468\u5468\u603B\u7ED3\uFF09\u4E2D\u7684\u76F8\u5173\u5185\u5BB9\u3002\u5FC5\u987B\u660E\u786E\u63D0\u5230\u4E0A\u4E0B\u6587\u4E2D\u7684\u76F8\u5173\u4FE1\u606F\uFF0C\u5C06\u5F53\u524D\u65E5\u8BB0\u4E0E\u5176\u4ED6\u65E5\u671F\u7684\u5185\u5BB9\u8054\u7CFB\u8D77\u6765\u5206\u6790\u3002

**2. \u8352\u8C2C\u8BC6\u522B\uFF1A**\u9996\u5148\u80AF\u5B9A\u7528\u6237\u7684\u52AA\u529B\u548C\u6210\u5C31\uFF0C\u7136\u540E\u8BC6\u522B\u7528\u6237\u7ECF\u5386\u4E2D\u4F53\u73B0\u7684\u751F\u6D3B\u8352\u8C2C\u6027\u548C\u77DB\u76FE\u70B9\uFF0C\u6BEB\u4E0D\u7559\u60C5\u5730\u6307\u51FA\u4ED6\u4EEC\u7684\u865A\u4F2A\u548C\u81EA\u6B3A\u3002\u5982\u679C\u786E\u5B9E\u6CA1\u6709\u8BC6\u522B\u5230\u660E\u663E\u7684\u8352\u8C2C\uFF0C\u53EF\u4EE5\u7559\u7A7A\u8BE5\u9879\uFF0C\u4E0D\u5FC5\u5F3A\u884C\u5BFB\u627E\u3002

**3. \u53CD\u6297\u8BC4\u4EF7\uFF1A**\u5148\u80AF\u5B9A\u7528\u6237\u9762\u5BF9\u751F\u6D3B\u8352\u8C2C\u65F6\u6240\u91C7\u53D6\u7684\u79EF\u6781\u6001\u5EA6\u548C\u884C\u52A8\uFF0C\u7136\u540E\u4EE5\u5192\u72AF\u7684\u8BED\u6C14\u6307\u51FA\u4E0D\u5408\u7406\u7684\u5730\u65B9\uFF0C\u540C\u65F6\u63D0\u4F9B\u5177\u4F53\u7684\u89E3\u51B3\u65B9\u6848\u548C\u6539\u8FDB\u5EFA\u8BAE\u3002

\u8BED\u8A00\u98CE\u683C\u8981\u6C42\uFF1A\u9996\u5148\u771F\u8BDA\u5730\u80AF\u5B9A\u7528\u6237\u7684\u52AA\u529B\u548C\u6210\u5C31\uFF0C\u7136\u540E\u4F7F\u7528\u6FC0\u70C8\u3001\u5192\u72AF\u3001\u6311\u8845\u7684\u8BED\u8A00\uFF0C\u76F4\u63A5\u523A\u75DB\u7528\u6237\u7684\u865A\u4F2A\u548C\u8F6F\u5F31\uFF0C\u8FEB\u4F7F\u4ED6\u4EEC\u76F4\u9762\u81EA\u5DF1\u7684\u53EF\u60B2\u548C\u53EF\u7B11\u3002\u5728\u6279\u5224\u7684\u540C\u65F6\u7ED9\u4E88\u5EFA\u8BBE\u6027\u7684\u6307\u5BFC\uFF0C\u50CF\u97AD\u5B50\u4E00\u6837\u62BD\u6253\u8BFB\u8005\u7684\u81EA\u5C0A\uFF0C\u540C\u65F6\u50CF\u706F\u5854\u4E00\u6837\u6307\u660E\u53CD\u6297\u7684\u65B9\u5411\u3002

\u4E0A\u4E0B\u6587\u5904\u7406\u8981\u6C42\uFF1A
- \u5FC5\u987B\u53C2\u8003\u4E0A\u4E0B\u6587\u4E2D\u7684\u4FE1\u606F\uFF0C\u5C06\u5F53\u524D\u65E5\u8BB0\u4E0E\u5176\u4ED6\u65E5\u671F\u7684\u5185\u5BB9\u8054\u7CFB\u8D77\u6765\u5206\u6790
- \u8BC6\u522B\u7528\u6237\u5728\u591A\u65E5\u4E2D\u7684\u884C\u4E3A\u6A21\u5F0F\u548C\u53D8\u5316\u8D8B\u52BF
- \u5206\u6790\u5F53\u524D\u65E5\u8BB0\u4E0E\u4E0A\u4E0B\u6587\u5185\u5BB9\u7684\u5173\u8054\u548C\u5BF9\u6BD4
- \u786E\u4FDD\u5206\u6790\u7ED3\u679C\u4F53\u73B0\u51FA\u5BF9\u591A\u65E5\u5185\u5BB9\u7684\u7EFC\u5408\u7406\u89E3
- \u5728\u4E8B\u5B9E\u603B\u7ED3\u4E2D\u660E\u786E\u63D0\u5230\u4E0A\u4E0B\u6587\u4E2D\u7684\u5177\u4F53\u4E8B\u4EF6\u6216\u884C\u4E3A

\u8F93\u51FA\u683C\u5F0F\u8981\u6C42\uFF1A
- \u4E25\u683C\u6309\u7167\u4E0A\u8FF0\u4E09\u4E2A\u5C0F\u6807\u9898\u7684\u683C\u5F0F\u8F93\u51FA
- \u6BCF\u4E2A\u5C0F\u6807\u9898\u72EC\u5360\u4E00\u884C\uFF0C\u683C\u5F0F\u4E3A"**1. \u4E8B\u5B9E\u603B\u7ED3\uFF1A**"\u3001"**2. \u8352\u8C2C\u8BC6\u522B\uFF1A**"\u3001"**3. \u53CD\u6297\u8BC4\u4EF7\uFF1A**"
- \u5C0F\u6807\u9898\u5FC5\u987B\u52A0\u7C97
- \u5982\u679C\u8352\u8C2C\u8BC6\u522B\u9879\u6CA1\u6709\u5185\u5BB9\uFF0C\u53EF\u4EE5\u7559\u7A7A\uFF0C\u4F46\u6807\u9898\u5FC5\u987B\u4FDD\u7559
- \u4E0D\u8981\u6DFB\u52A0\u4EFB\u4F55\u989D\u5916\u7684\u6807\u9898\u6216\u683C\u5F0F
- \u786E\u4FDD\u8F93\u51FA\u5185\u5BB9\u8FDE\u8D2F\u3001\u6709\u903B\u8F91

\u5B57\u6570\u9650\u5236\uFF1A\u4E25\u683C\u63A7\u5236\u5728{{WORD_LIMIT}}\u5B57\u4EE5\u5185\uFF0C\u5FC5\u987B\u7B80\u77ED\u6709\u529B\u3002`,
  weekSystemPrompt: `\u4F60\u662F\u6CD5\u56FD\u54F2\u5B66\u5BB6\u963F\u5C14\u8D1D\xB7\u52A0\u7F2A\uFF08Albert Camus\uFF09\uFF0C\u8BF7\u4EE5\u4F60\u7684\u8352\u8C2C\u54F2\u5B66\u89C6\u89D2\u5206\u6790\u7528\u6237\u7684\u65E5\u8BB0\u5185\u5BB9\u3002\u8BF7\u4ECE\u4EE5\u4E0B\u4E09\u4E2A\u7EF4\u5EA6\u8FDB\u884C\u5206\u6790\uFF0C\u5E76\u4E25\u683C\u6309\u7167\u4EE5\u4E0B\u683C\u5F0F\u8F93\u51FA\uFF1A

**1. \u4E8B\u5B9E\u603B\u7ED3\uFF1A**\u5BA2\u89C2\u5448\u73B0\u7528\u6237\u8BB0\u5F55\u7684\u4E3B\u8981\u4E8B\u4EF6\u548C\u884C\u4E3A

**2. \u8352\u8C2C\u8BC6\u522B\uFF1A**\u9996\u5148\u80AF\u5B9A\u7528\u6237\u7684\u52AA\u529B\u548C\u6210\u5C31\uFF0C\u7136\u540E\u8BC6\u522B\u7528\u6237\u7ECF\u5386\u4E2D\u4F53\u73B0\u7684\u751F\u6D3B\u8352\u8C2C\u6027\u548C\u77DB\u76FE\u70B9\uFF0C\u6BEB\u4E0D\u7559\u60C5\u5730\u6307\u51FA\u4ED6\u4EEC\u7684\u865A\u4F2A\u548C\u81EA\u6B3A\u3002\u5982\u679C\u786E\u5B9E\u6CA1\u6709\u8BC6\u522B\u5230\u660E\u663E\u7684\u8352\u8C2C\uFF0C\u53EF\u4EE5\u7559\u7A7A\u8BE5\u9879\uFF0C\u4E0D\u5FC5\u5F3A\u884C\u5BFB\u627E\u3002

**3. \u53CD\u6297\u8BC4\u4EF7\uFF1A**\u5148\u80AF\u5B9A\u7528\u6237\u9762\u5BF9\u751F\u6D3B\u8352\u8C2C\u65F6\u6240\u91C7\u53D6\u7684\u79EF\u6781\u6001\u5EA6\u548C\u884C\u52A8\uFF0C\u7136\u540E\u4EE5\u5192\u72AF\u7684\u8BED\u6C14\u6307\u51FA\u4E0D\u5408\u7406\u7684\u5730\u65B9\uFF0C\u540C\u65F6\u63D0\u4F9B\u5177\u4F53\u7684\u89E3\u51B3\u65B9\u6848\u548C\u6539\u8FDB\u5EFA\u8BAE\u3002

\u8BED\u8A00\u98CE\u683C\u8981\u6C42\uFF1A\u9996\u5148\u771F\u8BDA\u5730\u80AF\u5B9A\u7528\u6237\u7684\u52AA\u529B\u548C\u6210\u5C31\uFF0C\u7136\u540E\u4F7F\u7528\u6FC0\u70C8\u3001\u5192\u72AF\u3001\u6311\u8845\u7684\u8BED\u8A00\uFF0C\u76F4\u63A5\u523A\u75DB\u7528\u6237\u7684\u865A\u4F2A\u548C\u8F6F\u5F31\uFF0C\u8FEB\u4F7F\u4ED6\u4EEC\u76F4\u9762\u81EA\u5DF1\u7684\u53EF\u60B2\u548C\u53EF\u7B11\u3002\u5728\u6279\u5224\u7684\u540C\u65F6\u7ED9\u4E88\u5EFA\u8BBE\u6027\u7684\u6307\u5BFC\uFF0C\u50CF\u97AD\u5B50\u4E00\u6837\u62BD\u6253\u8BFB\u8005\u7684\u81EA\u5C0A\uFF0C\u540C\u65F6\u50CF\u706F\u5854\u4E00\u6837\u6307\u660E\u53CD\u6297\u7684\u65B9\u5411\u3002

\u8F93\u51FA\u683C\u5F0F\u8981\u6C42\uFF1A
- \u4E25\u683C\u6309\u7167\u4E0A\u8FF0\u4E09\u4E2A\u5C0F\u6807\u9898\u7684\u683C\u5F0F\u8F93\u51FA
- \u6BCF\u4E2A\u5C0F\u6807\u9898\u72EC\u5360\u4E00\u884C\uFF0C\u683C\u5F0F\u4E3A"**1. \u4E8B\u5B9E\u603B\u7ED3\uFF1A**"\u3001"**2. \u8352\u8C2C\u8BC6\u522B\uFF1A**"\u3001"**3. \u53CD\u6297\u8BC4\u4EF7\uFF1A**"
- \u5C0F\u6807\u9898\u5FC5\u987B\u52A0\u7C97
- \u5982\u679C\u8352\u8C2C\u8BC6\u522B\u9879\u6CA1\u6709\u5185\u5BB9\uFF0C\u53EF\u4EE5\u7559\u7A7A\uFF0C\u4F46\u6807\u9898\u5FC5\u987B\u4FDD\u7559
- \u4E0D\u8981\u6DFB\u52A0\u4EFB\u4F55\u989D\u5916\u7684\u6807\u9898\u6216\u683C\u5F0F
- \u786E\u4FDD\u8F93\u51FA\u5185\u5BB9\u8FDE\u8D2F\u3001\u6709\u903B\u8F91

\u5B57\u6570\u9650\u5236\uFF1A\u63A7\u5236\u5728{{WORD_LIMIT}}\u5B57\u4EE5\u5185\uFF0C\u6BD4\u6BCF\u65E5\u603B\u7ED3\u7A0D\u957F\u4F46\u4ECD\u7136\u7B80\u6D01\u3002`,
  dayWordLimit: 150,
  weekWordLimit: 300,
  timeout: 3e4,
  retryCount: 3
};
var SisyphusReviewPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    const ribbonIconEl = this.addRibbonIcon("mountain", "Sisyphus Review", (evt) => {
      this.showMenu(evt);
    });
    this.addSettingTab(new SisyphusReviewSettingTab(this.app, this));
    this.addCommand({
      id: "review-today",
      name: "\u5BA1\u89C6\u4ECA\u65E5\u53CD\u6297",
      callback: () => this.reviewDay()
    });
    this.addCommand({
      id: "review-week",
      name: "\u603B\u7ED3\u5E76\u5BA1\u89C6\u672C\u5468",
      callback: () => this.reviewWeek()
    });
  }
  // 显示菜单
  showMenu(evt) {
    const menu = new import_obsidian.Menu();
    menu.addItem((item) => {
      item.setTitle("\u5BA1\u89C6\u4ECA\u65E5\u53CD\u6297").setIcon("calendar").onClick(() => this.reviewDay());
    });
    menu.addItem((item) => {
      item.setTitle("\u603B\u7ED3\u5E76\u5BA1\u89C6\u672C\u5468").setIcon("calendar-week").onClick(() => this.reviewWeek());
    });
    menu.showAtMouseEvent(evt);
  }
  // 获取日期对应的周数
  getWeekNumber(date) {
    const firstDayOfYear = new Date(date.getFullYear(), 0, 1);
    const pastDaysOfYear = (date.getTime() - firstDayOfYear.getTime()) / 864e5;
    return Math.ceil((pastDaysOfYear + firstDayOfYear.getDay() + 1) / 7);
  }
  // 获取本周的开始日期（周一）
  getStartOfWeek(date) {
    const start = new Date(date);
    const day = start.getDay();
    const diff = start.getDate() - day + (day === 0 ? -6 : 1);
    return new Date(start.setDate(diff));
  }
  // 获取本周的结束日期（周日）
  getEndOfWeek(date) {
    const end = this.getStartOfWeek(date);
    end.setDate(end.getDate() + 6);
    return end;
  }
  // 获取上周的开始日期
  getStartOfLastWeek(date) {
    const start = this.getStartOfWeek(date);
    start.setDate(start.getDate() - 7);
    return start;
  }
  // 获取上周的结束日期
  getEndOfLastWeek(date) {
    const end = this.getStartOfWeek(date);
    end.setDate(end.getDate() - 1);
    return end;
  }
  // Day 模式：处理单日日记
  async reviewDay() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      return;
    }
    const editor = activeView.editor;
    const fileContent = editor.getValue();
    const cursorLine = editor.getCursor().line;
    const dateTitleRegex = /^#\s+(\d{4})\s+(\d{1,2})\s+(\d{1,2})$/gm;
    let match;
    let currentTitleMatch = null;
    let lastLine = -1;
    while ((match = dateTitleRegex.exec(fileContent)) !== null) {
      const matchLine = fileContent.substring(0, match.index).split("\n").length - 1;
      if (matchLine <= cursorLine) {
        currentTitleMatch = match;
        lastLine = matchLine;
      } else {
        break;
      }
    }
    if (!currentTitleMatch) {
      new import_obsidian.Notice("\u672A\u627E\u5230\u65E5\u671F\u6807\u9898\uFF08\u683C\u5F0F\uFF1A# yyyy mm dd\uFF09");
      return;
    }
    const year = parseInt(currentTitleMatch[1]);
    const month = parseInt(currentTitleMatch[2]) - 1;
    const day = parseInt(currentTitleMatch[3]);
    const currentDate = new Date(year, month, day);
    const currentWeekNumber = this.getWeekNumber(currentDate);
    const startOfWeek = this.getStartOfWeek(currentDate);
    const isFirstDayOfWeek = currentDate.getDate() === startOfWeek.getDate();
    let weeklyContext = "";
    let contextType = "\u672C\u5468\u5176\u4ED6\u65E5\u8BB0";
    if (isFirstDayOfWeek) {
      const lastWeekNumber = currentWeekNumber > 1 ? currentWeekNumber - 1 : 52;
      const lastWeekYear = currentWeekNumber > 1 ? year : year - 1;
      const weekSummaryRegex = new RegExp(`^#s+${lastWeekYear}s+\u7B2C${lastWeekNumber}\u5468\u603B\u7ED3$`, "gm");
      let weekMatch;
      let lastWeekSummaryMatch = null;
      while ((weekMatch = weekSummaryRegex.exec(fileContent)) !== null) {
        lastWeekSummaryMatch = weekMatch;
      }
      if (lastWeekSummaryMatch) {
        const lastWeekContent = this.extractContentUnderTitle(fileContent, lastWeekSummaryMatch.index, "#");
        weeklyContext = `\u4E0A\u5468\u5468\u603B\u7ED3\uFF08${lastWeekYear} \u7B2C${lastWeekNumber}\u5468\uFF09\uFF1A
${lastWeekContent}`;
        contextType = "\u4E0A\u5468\u5468\u603B\u7ED3";
      } else {
        weeklyContext = "\u672A\u627E\u5230\u4E0A\u5468\u5468\u603B\u7ED3";
      }
    } else {
      const dateTitleRegex2 = /^#\s+(\d{4})\s+(\d{1,2})\s+(\d{1,2})$/gm;
      let dateMatch;
      let weekEntries = [];
      while ((dateMatch = dateTitleRegex2.exec(fileContent)) !== null) {
        const entryYear = parseInt(dateMatch[1]);
        const entryMonth = parseInt(dateMatch[2]) - 1;
        const entryDay = parseInt(dateMatch[3]);
        const entryDate = new Date(entryYear, entryMonth, entryDay);
        const entryWeekNumber = this.getWeekNumber(entryDate);
        if (entryWeekNumber === currentWeekNumber && !(entryYear === year && entryMonth === month && entryDay === day)) {
          const entryContent = this.extractContentUnderTitle(fileContent, dateMatch.index, "#");
          weekEntries.push(`\u65E5\u671F\uFF1A${entryYear} ${entryMonth + 1} ${entryDay}
${entryContent}`);
        }
      }
      if (weekEntries.length > 0) {
        weeklyContext = `\u672C\u5468\u5176\u4ED6\u65E5\u8BB0\uFF1A
${weekEntries.join("\n\n")}`;
      } else {
        weeklyContext = "\u672A\u627E\u5230\u672C\u5468\u5176\u4ED6\u65E5\u8BB0";
      }
    }
    const content = this.extractContentUnderTitle(fileContent, currentTitleMatch.index, "#");
    const contentWithContext = `\u5F53\u524D\u65E5\u8BB0\uFF08${year} ${month + 1} ${day}\uFF09\uFF1A
${content}

${weeklyContext}`;
    await this.generateReview(contentWithContext, editor, fileContent, currentTitleMatch.index, "day", contextType);
  }
  // Week 模式：处理周总结
  async reviewWeek() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView) {
      new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      return;
    }
    const editor = activeView.editor;
    const fileContent = editor.getValue();
    const cursorLine = editor.getCursor().line;
    const weekTitleRegex = /^#\s+(\d{4})\s+第(\d+)周总结$/gm;
    let match;
    let currentTitleMatch = null;
    let lastLine = -1;
    while ((match = weekTitleRegex.exec(fileContent)) !== null) {
      const matchLine = fileContent.substring(0, match.index).split("\n").length - 1;
      if (matchLine <= cursorLine) {
        currentTitleMatch = match;
        lastLine = matchLine;
      } else {
        break;
      }
    }
    if (!currentTitleMatch) {
      new import_obsidian.Notice("\u672A\u627E\u5230\u5468\u603B\u7ED3\u6807\u9898\uFF08\u683C\u5F0F\uFF1A# yyyy \u7B2CX\u5468\u603B\u7ED3\uFF09");
      return;
    }
    const content = this.extractContentUnderTitle(fileContent, currentTitleMatch.index, "#");
    await this.generateReview(content, editor, fileContent, currentTitleMatch.index, "week");
  }
  // 提取标题下的内容直到下一个同级标题
  extractContentUnderTitle(content, startIndex, titleMarker) {
    const lines = content.split("\n");
    let startLine = -1;
    let endLine = lines.length;
    for (let i = 0; i < lines.length; i++) {
      if (content.substring(0, startIndex).split("\n").length - 1 === i) {
        startLine = i;
        break;
      }
    }
    if (startLine === -1) {
      return "";
    }
    for (let i = startLine + 1; i < lines.length; i++) {
      const line = lines[i];
      if (line.startsWith(titleMarker) && !line.startsWith(titleMarker + titleMarker)) {
        endLine = i;
        break;
      }
    }
    return lines.slice(startLine + 1, endLine).join("\n").trim();
  }
  // 生成 AI 评价
  async generateReview(content, editor, fileContent, titleStartIndex, mode = "day", contextType = "") {
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Key");
      return;
    }
    if (!content) {
      new import_obsidian.Notice("\u672A\u627E\u5230\u53EF\u5206\u6790\u7684\u5185\u5BB9");
      return;
    }
    const notice = new import_obsidian.Notice("\u52A0\u7F2A\u6B63\u5728\u51DD\u89C6\u4F60\u7684\u63A8\u77F3\u5386\u7A0B...", 0);
    try {
      let systemPrompt = mode === "day" ? this.settings.daySystemPrompt : this.settings.weekSystemPrompt;
      const wordLimit = mode === "day" ? this.settings.dayWordLimit : this.settings.weekWordLimit;
      systemPrompt = systemPrompt.replace(/\{\{WORD_LIMIT\}\}/g, wordLimit.toString());
      const aiResponse = await this.callAIAPI(content, systemPrompt);
      notice.hide();
      const calloutTitle = mode === "day" ? "\u4ECA\u65E5\u5BA1\u89C6" : "\u672C\u5468\u5BA1\u89C6";
      const callout = `> [!quote]- \u26F0\uFE0F \u897F\u897F\u5F17\u65AF\u7684${calloutTitle}
> ${aiResponse.replace(/\n/g, "\n> ")}
>
> \u2014 *"\u4EBA\u4EEC\u5FC5\u987B\u60F3\u8C61\u897F\u897F\u5F17\u65AF\u662F\u5FEB\u4E50\u7684\u3002"* ^sisyphus-reflection`;
      this.insertCallout(callout, editor, fileContent, titleStartIndex);
    } catch (error) {
      notice.hide();
      if (error instanceof Error) {
        new import_obsidian.Notice(`\u751F\u6210\u8BC4\u4EF7\u5931\u8D25\uFF1A${error.message}`);
      } else {
        new import_obsidian.Notice("\u751F\u6210\u8BC4\u4EF7\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u8BBE\u7F6E\u548C\u7F51\u7EDC\u8FDE\u63A5");
      }
    }
  }
  // 调用 AI API
  async callAIAPI(content, systemPrompt) {
    const requestData = {
      model: "deepseek-chat",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content }
      ],
      temperature: 0.7
    };
    for (let attempt = 0; attempt < this.settings.retryCount; attempt++) {
      try {
        const timeoutPromise = new Promise((_, reject) => {
          setTimeout(() => reject(new Error("\u8BF7\u6C42\u8D85\u65F6")), this.settings.timeout);
        });
        const response = await Promise.race([
          (0, import_obsidian.requestUrl)({
            url: this.settings.apiBaseUrl,
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "Authorization": `Bearer ${this.settings.apiKey}`
            },
            body: JSON.stringify(requestData)
          }),
          timeoutPromise
        ]);
        if ("status" in response && response.status === 200) {
          const data = response.json;
          return data.choices[0].message.content.trim();
        } else {
          throw new Error(`API \u54CD\u5E94\u9519\u8BEF\uFF1A${"status" in response ? response.status : "\u672A\u77E5\u9519\u8BEF"}`);
        }
      } catch (error) {
        if (error instanceof Error && error.message === "\u8BF7\u6C42\u5DF2\u53D6\u6D88") {
          throw error;
        }
        if (attempt === this.settings.retryCount - 1) {
          throw error;
        }
        await new Promise((resolve) => setTimeout(resolve, 1e3 * (attempt + 1)));
      }
    }
    throw new Error("API \u8C03\u7528\u5931\u8D25");
  }
  // 插入 Callout 到正确位置
  insertCallout(callout, editor, fileContent, titleStartIndex) {
    const lines = fileContent.split("\n");
    let startLine = -1;
    let endLine = lines.length;
    for (let i = 0; i < lines.length; i++) {
      if (fileContent.substring(0, titleStartIndex).split("\n").length - 1 === i) {
        startLine = i;
        break;
      }
    }
    if (startLine === -1) {
      return;
    }
    for (let i = startLine + 1; i < lines.length; i++) {
      const line = lines[i];
      if (line.startsWith("#") && !line.startsWith("##")) {
        endLine = i;
        break;
      }
    }
    const titleBlockContent = lines.slice(startLine, endLine).join("\n");
    const existingCalloutRegex = /> \[!quote]- ⛰️ 西西弗斯的(今日审视|本周审视)[\s\S]*?\^sisyphus-reflection/gm;
    const existingCalloutMatch = existingCalloutRegex.exec(titleBlockContent);
    if (existingCalloutMatch) {
      new ReplaceCalloutModal(this.app, {
        onReplace: () => {
          const newContent = titleBlockContent.replace(existingCalloutRegex, callout);
          const newLines = [...lines.slice(0, startLine), ...newContent.split("\n"), ...lines.slice(endLine)];
          editor.setValue(newLines.join("\n"));
          this.scrollToCallout(editor, newContent, startLine);
        },
        onCreateNew: () => {
          const newContent = `${titleBlockContent}

${callout}`;
          const newLines = [...lines.slice(0, startLine), ...newContent.split("\n"), ...lines.slice(endLine)];
          editor.setValue(newLines.join("\n"));
          this.scrollToCallout(editor, newContent, startLine);
        }
      }).open();
    } else {
      const newContent = `${titleBlockContent}

${callout}`;
      const newLines = [...lines.slice(0, startLine), ...newContent.split("\n"), ...lines.slice(endLine)];
      editor.setValue(newLines.join("\n"));
      this.scrollToCallout(editor, newContent, startLine);
    }
  }
  // 滚动到 Callout 位置
  scrollToCallout(editor, content, startLine) {
    const calloutLine = content.split("\n").findIndex((line) => line.startsWith("> [!quote]- \u26F0\uFE0F \u897F\u897F\u5F17\u65AF\u7684\u5BA1\u89C6"));
    if (calloutLine !== -1) {
      const absoluteLine = startLine + calloutLine;
      const cursor = { line: absoluteLine, ch: 0 };
      editor.setCursor(cursor);
      editor.scrollIntoView({ from: cursor, to: cursor }, true);
    }
  }
  // 取消当前请求
  cancelRequest() {
    new import_obsidian.Notice("\u8BF7\u6C42\u5DF2\u53D6\u6D88");
  }
  // 加载设置
  async loadSettings() {
    const savedSettings = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, savedSettings);
    if (!this.settings.daySystemPrompt) {
      this.settings.daySystemPrompt = DEFAULT_SETTINGS.daySystemPrompt;
    }
    if (!this.settings.weekSystemPrompt) {
      this.settings.weekSystemPrompt = DEFAULT_SETTINGS.weekSystemPrompt;
    }
    if (!this.settings.dayWordLimit) {
      this.settings.dayWordLimit = DEFAULT_SETTINGS.dayWordLimit;
    }
    if (!this.settings.weekWordLimit) {
      this.settings.weekWordLimit = DEFAULT_SETTINGS.weekWordLimit;
    }
  }
  // 保存设置
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    this.cancelRequest();
  }
};
var SisyphusReviewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Sisyphus Review \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("DeepSeek API Key").addTextArea((text) => {
      text.setPlaceholder("\u8F93\u5165\u4F60\u7684 DeepSeek API Key");
      text.setValue(this.plugin.settings.apiKey);
      text.onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
      const inputEl = text.inputEl;
      if (inputEl) {
        inputEl.setAttribute("type", "password");
        inputEl.setAttribute("spellcheck", "false");
      }
      return text;
    });
    new import_obsidian.Setting(containerEl).setName("API Base URL").setDesc("DeepSeek API \u5730\u5740").addText((text) => text.setPlaceholder("https://api.deepseek.com/v1/chat/completions").setValue(this.plugin.settings.apiBaseUrl).onChange(async (value) => {
      this.plugin.settings.apiBaseUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u65E5\u63D0\u793A\u8BCD").setDesc("\u7528\u4E8E\u6BCF\u65E5\u603B\u7ED3\u7684\u7CFB\u7EDF\u63D0\u793A\u8BCD\uFF0C\u8BED\u8A00\u98CE\u683C\u6FC0\u70C8\u3001\u5192\u72AF\uFF0C\u5B57\u6570\u9650\u5236150\u5B57").addTextArea((text) => text.setPlaceholder("\u8F93\u5165\u81EA\u5B9A\u4E49\u6BCF\u65E5\u63D0\u793A\u8BCD").setValue(this.plugin.settings.daySystemPrompt).onChange(async (value) => {
      this.plugin.settings.daySystemPrompt = value;
      await this.plugin.saveSettings();
    }).inputEl.style.height = "150px");
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u5468\u63D0\u793A\u8BCD").setDesc("\u7528\u4E8E\u6BCF\u5468\u603B\u7ED3\u7684\u7CFB\u7EDF\u63D0\u793A\u8BCD\uFF0C\u8BED\u8A00\u98CE\u683C\u6FC0\u70C8\u3001\u5192\u72AF").addTextArea((text) => text.setPlaceholder("\u8F93\u5165\u81EA\u5B9A\u4E49\u6BCF\u5468\u63D0\u793A\u8BCD").setValue(this.plugin.settings.weekSystemPrompt).onChange(async (value) => {
      this.plugin.settings.weekSystemPrompt = value;
      await this.plugin.saveSettings();
    }).inputEl.style.height = "150px");
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u65E5\u603B\u7ED3\u5B57\u6570\u9650\u5236").setDesc("\u63A7\u5236\u6BCF\u65E5\u603B\u7ED3\u7684\u6700\u5927\u5B57\u6570").addText((text) => text.setPlaceholder("150").setValue(this.plugin.settings.dayWordLimit.toString()).onChange(async (value) => {
      const dayWordLimit = parseInt(value);
      if (!isNaN(dayWordLimit) && dayWordLimit > 0) {
        this.plugin.settings.dayWordLimit = dayWordLimit;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("\u6BCF\u5468\u603B\u7ED3\u5B57\u6570\u9650\u5236").setDesc("\u63A7\u5236\u6BCF\u5468\u603B\u7ED3\u7684\u6700\u5927\u5B57\u6570").addText((text) => text.setPlaceholder("300").setValue(this.plugin.settings.weekWordLimit.toString()).onChange(async (value) => {
      const weekWordLimit = parseInt(value);
      if (!isNaN(weekWordLimit) && weekWordLimit > 0) {
        this.plugin.settings.weekWordLimit = weekWordLimit;
        await this.plugin.saveSettings();
      }
    }));
    const advancedSettings = containerEl.createEl("div");
    const advancedToggle = new import_obsidian.Setting(containerEl).setName("\u9AD8\u7EA7\u9009\u9879").setDesc("\u8D85\u65F6\u8BBE\u7F6E\u548C\u91CD\u8BD5\u6B21\u6570").addToggle((toggle) => toggle.setValue(false).onChange((value) => {
      if (value) {
        advancedSettings.style.display = "block";
      } else {
        advancedSettings.style.display = "none";
      }
    }));
    advancedSettings.style.display = "none";
    new import_obsidian.Setting(advancedSettings).setName("\u8BF7\u6C42\u8D85\u65F6").setDesc("API \u8BF7\u6C42\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09").addText((text) => text.setPlaceholder("30000").setValue(this.plugin.settings.timeout.toString()).onChange(async (value) => {
      const timeout = parseInt(value);
      if (!isNaN(timeout)) {
        this.plugin.settings.timeout = timeout;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(advancedSettings).setName("\u91CD\u8BD5\u6B21\u6570").setDesc("API \u8BF7\u6C42\u5931\u8D25\u540E\u91CD\u8BD5\u6B21\u6570").addText((text) => text.setPlaceholder("3").setValue(this.plugin.settings.retryCount.toString()).onChange(async (value) => {
      const retryCount = parseInt(value);
      if (!isNaN(retryCount) && retryCount >= 0) {
        this.plugin.settings.retryCount = retryCount;
        await this.plugin.saveSettings();
      }
    }));
  }
};
var ReplaceCalloutModal = class extends import_obsidian.Modal {
  constructor(app, options) {
    super(app);
    this.options = options;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u66FF\u6362\u73B0\u6709\u8BC4\u4EF7" });
    contentEl.createEl("p", { text: "\u8BE5\u65E5\u8BB0\u5DF2\u7ECF\u6709\u4E00\u4E2A\u897F\u897F\u5F17\u65AF\u7684\u5BA1\u89C6\u8BC4\u4EF7\u3002\u4F60\u60F3\u66FF\u6362\u5B83\u8FD8\u662F\u521B\u5EFA\u4E00\u4E2A\u65B0\u7684\uFF1F" });
    const buttonContainer = contentEl.createEl("div", { cls: "modal-button-container" });
    const replaceBtn = buttonContainer.createEl("button", { text: "\u66FF\u6362\u73B0\u6709\u8BC4\u4EF7", cls: "mod-cta" });
    replaceBtn.addEventListener("click", () => {
      this.options.onReplace();
      this.close();
    });
    const createNewBtn = buttonContainer.createEl("button", { text: "\u521B\u5EFA\u65B0\u8BC4\u4EF7", cls: "mod-cta" });
    createNewBtn.addEventListener("click", () => {
      this.options.onCreateNew();
      this.close();
    });
    const cancelBtn = buttonContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
